#!/usr/bin/env bash

# Setup shared .spago and output directories

set -e
set -u
set -o pipefail

build_dir="./_build"

if [ -d ${build_dir} ]; then
    echo "Found existing ${build_dir}; removing..."
    rm -rf ${build_dir}
fi

mkdir -p "${build_dir}"/{_output,_spago}

cp -R ./exercises/practice "${build_dir}"

for exercise_dir in "${build_dir}/practice/"*; do
    exercise_slug=$(basename "${exercise_dir}")

    echo ">> Working on practice/${exercise_slug}"

    pushd "${exercise_dir}" > /dev/null

    cp ./examples/src/*.purs ./src

    # Use a shared output and .spago directory to avoid rebuilding shared
    # dependencies. These directories are ideal candidates for caching on
    # GitHub CI...
    ln -s ../../_output ./output
    ln -s ../../_spago ./.spago

    # XXX(emiel) Go for real pascal case
    exercise_pascal=$(echo "${exercise_slug}" | tr '[:lower:]' '[:upper:]' | sed -e "s/-//g")

    # Substitute generic module name to avoid module name clash in test modules
    cp ./test/Main.purs ./test/Main.purs.orig
    sed "s/module Test.Main/module Test.${exercise_pascal}/" < ./test/Main.purs.orig > ./test/Main.purs

    # Execute the test
    spago test -m "Test.${exercise_pascal}"

    popd > /dev/null
done
