#!/usr/bin/env bash

# Ensure all exercises use the same spago.yaml configuration (except for the
# package name which differs per exercise). We compare the files after stripping
# the name line.

set -e
set -o pipefail
set -u

strip_name() {
    sed '/^  name:/d' "$1"
}

# We use spago.yaml from the template project as the source of truth.
template_digest=$(strip_name ./template/spago.yaml | openssl dgst -sha256)

rc=0

for yaml_file in ./exercises/{concept,practice}/*/spago.yaml; do
    exercise_digest=$(strip_name "${yaml_file}" | openssl dgst -sha256)

    if [ "$template_digest" != "$exercise_digest" ]; then
        rc=1
        echo "${yaml_file} deviates from template"
    fi
done

exit $rc
